In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ebrahimelgazar/new-york-city-airbnb-market", output_dir="datasets/new-york-city-airbnb-market")

print("Path to dataset files:", path)

Downloading to datasets/new-york-city-airbnb-market\2.archive...

100%|██████████| 1.37M/1.37M [00:01<00:00, 1.07MB/s]

Extracting files...
Path to dataset files: datasets/new-york-city-airbnb-market

# Importing data

In [38]:
import pandas as pd 
import numpy as np 


# load the dataset 

review_df = pd.read_csv("datasets/new-york-city-airbnb-market/airbnb_last_review.csv")
price_df = pd.read_csv("datasets/new-york-city-airbnb-market/airbnb_price.csv")
room_df = pd.read_excel("datasets/new-york-city-airbnb-market/airbnb_room_type.xlsx")

print('Review dataset shape:', review_df.shape)
print('Price dataset shape:', price_df.shape)
print('Room dataset shape:', room_df.shape)

Review dataset shape: (25209, 3)
Price dataset shape: (25209, 3)
Room dataset shape: (25209, 3)

In [40]:
review_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0    listing_id  25209 non-null  int64
 1   host_name    25201 non-null  str
 2   last_review  25209 non-null  str
dtypes: int64(1), str(2)
memory usage: 591.0 KB

In [39]:
review_df.head()

    listing_id    host_name   last_review
0         2595     Jennifer   May 21 2019
1         3831  LisaRoxanne  July 05 2019
2         5099        Chris  June 22 2019
3         5178     Shunichi  June 24 2019
4         5238          Ben  June 09 2019

In [58]:
review_df.columns

Index([' listing_id', 'host_name', 'last_review'], dtype='str')

In [59]:
# processing the review dataset 

# 0. stripping the leading and trailing spaces from the columns names 
review_df.columns = review_df.columns.str.strip(' ')

# 1. convert the date column to datetime format
review_df['last_review'] = pd.to_datetime(review_df['last_review'] , errors = 'coerce').dt.date

# 2. changing the dtype of listings_id to string
review_df['listing_id'] = review_df['listing_id'].astype(str)

# 3. checking for missing values 
missing_values = review_df.isnull().sum()

# 4. checking duplicated values 
duplicated_values = review_df.duplicated().sum()

print(review_df.head())
print("Missing values in each column:")
print(missing_values)
print("Duplicated values:")
print(duplicated_values)

  listing_id    host_name last_review
0       2595     Jennifer  2019-05-21
1       3831  LisaRoxanne  2019-07-05
2       5099        Chris  2019-06-22
3       5178     Shunichi  2019-06-24
4       5238          Ben  2019-06-09
Missing values in each column:
listing_id     0
host_name      8
last_review    0
dtype: int64
Duplicated values:
0

In [42]:
price_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  str
 2   nbhood_full  25209 non-null  str
dtypes: int64(1), str(2)
memory usage: 591.0 KB

In [43]:
price_df.head()

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [44]:
price_df.columns

Index(['listing_id', 'price', 'nbhood_full'], dtype='str')

In [45]:
# processing the review dataset 

# 0. stripping the leading and trailing spaces from the columns names 
price_df.columns = price_df.columns.str.strip(' ')

# 1. removing the $ sign from the price column and converting it to numeric
price_df['price'] = price_df['price'].str.strip('dollars').astype(float)

# 2. changing the dtype of listings_id to string
price_df['listing_id'] = price_df['listing_id'].astype(str)

# 3. checking for missing values 
missing_values = price_df.isnull().sum()

# 4. checking duplicated values 
duplicated_values = price_df.duplicated().sum()
print(price_df.head())
print("Missing values in each column:")
print(missing_values)
print("Duplicated values:")
print(duplicated_values)

  listing_id  price                nbhood_full
0       2595  225.0         Manhattan, Midtown
1       3831   89.0     Brooklyn, Clinton Hill
2       5099  200.0     Manhattan, Murray Hill
3       5178   79.0  Manhattan, Hell's Kitchen
4       5238  150.0       Manhattan, Chinatown
Missing values in each column:
listing_id     0
price          0
nbhood_full    0
dtype: int64
Duplicated values:
0

In [46]:
room_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  str
dtypes: int64(1), object(1), str(1)
memory usage: 591.0+ KB

In [47]:
room_df.head()

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [48]:
room_df.columns

Index(['listing_id', 'description', 'room_type'], dtype='str')

In [49]:
len(room_df['description'].unique()) , len(room_df['room_type'].unique())

(24947, 9)

In [50]:
# 1. converting the description column to string type 
room_df['description'] = room_df['description'].astype(str)

# 2. converting the listing_id to string type 
room_df['listing_id'] = room_df['listing_id'].astype(str)

# 3. coverting the room_type column into categorical type 
room_df['room_type'] = room_df['room_type'].astype('category')

# 4. checking for missing values 
missing_values = room_df.isnull().sum()
# 5. checking for duplicated values
duplicated_values = room_df.duplicated().sum()

print(room_df.head())
print("Missing values in each column:")
print(missing_values)
print("Duplicated values:")
print(duplicated_values)

  listing_id                                description        room_type
0       2595                      Skylit Midtown Castle  Entire home/apt
1       3831            Cozy Entire Floor of Brownstone  Entire home/apt
2       5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3       5178            Large Furnished Room Near B'way     private room
4       5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
Missing values in each column:
listing_id      0
description    10
room_type       0
dtype: int64
Duplicated values:
0

In [35]:
room_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  str
 1   description  25199 non-null  str
 2   room_type    25209 non-null  category
dtypes: category(1), str(2)
memory usage: 418.7 KB

# Combining data

In [51]:
df_all_concat = pd.concat([review_df , price_df , room_df] , axis = 1)

print(df_all_concat.head())
print(len(df_all_concat.columns))

    listing_id    host_name   last_review listing_id  price  \
0         2595     Jennifer   May 21 2019       2595  225.0
1         3831  LisaRoxanne  July 05 2019       3831   89.0
2         5099        Chris  June 22 2019       5099  200.0
3         5178     Shunichi  June 24 2019       5178   79.0
4         5238          Ben  June 09 2019       5238  150.0

                 nbhood_full listing_id  \
0         Manhattan, Midtown       2595
1     Brooklyn, Clinton Hill       3831
2     Manhattan, Murray Hill       5099
3  Manhattan, Hell's Kitchen       5178
4       Manhattan, Chinatown       5238

                                 description        room_type
0                      Skylit Midtown Castle  Entire home/apt
1            Cozy Entire Floor of Brownstone  Entire home/apt
2  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3            Large Furnished Room Near B'way     private room
4         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
9

| how     | meaning            |
| ------- | ------------------ |
| `inner` | only matching rows |
| `left`  | keep all from df1  |
| `right` | keep all from df2  |
| `outer` | keep everything    |

In [55]:
price_df

      listing_id  price                 nbhood_full
0           2595  225.0          Manhattan, Midtown
1           3831   89.0      Brooklyn, Clinton Hill
2           5099  200.0      Manhattan, Murray Hill
3           5178   79.0   Manhattan, Hell's Kitchen
4           5238  150.0        Manhattan, Chinatown
...          ...    ...                         ...
25204   36425863  129.0  Manhattan, Upper East Side
25205   36427429   45.0            Queens, Flushing
25206   36438336  235.0  Staten Island, Great Kills
25207   36442252  100.0           Bronx, Mott Haven
25208   36455809   30.0          Brooklyn, Bushwick

[25209 rows x 3 columns]

In [63]:
df_all_merge = review_df.merge(price_df , on = 'listing_id', how = 'inner').merge(room_df , on = 'listing_id' , how = 'inner')

print(df_all_merge.head())
print(len(df_all_merge.columns))
print('Shape of merged dataset:', df_all_merge.shape)

  listing_id    host_name last_review  price                nbhood_full  \
0       2595     Jennifer  2019-05-21  225.0         Manhattan, Midtown
1       3831  LisaRoxanne  2019-07-05   89.0     Brooklyn, Clinton Hill
2       5099        Chris  2019-06-22  200.0     Manhattan, Murray Hill
3       5178     Shunichi  2019-06-24   79.0  Manhattan, Hell's Kitchen
4       5238          Ben  2019-06-09  150.0       Manhattan, Chinatown

                                 description        room_type
0                      Skylit Midtown Castle  Entire home/apt
1            Cozy Entire Floor of Brownstone  Entire home/apt
2  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3            Large Furnished Room Near B'way     private room
4         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
7
Shape of merged dataset: (25209, 7)

In [64]:
df_all_merge.head()

,listing_id,host_name,last_review,price,nbhood_full,description,room_type
0,2595,Jennifer,2019-05-21,225.0,"Manhattan, Midtown",Skylit Midtown Castle,Entire home/apt
1,3831,LisaRoxanne,2019-07-05,89.0,"Brooklyn, Clinton Hill",Cozy Entire Floor of Brownstone,Entire home/apt
2,5099,Chris,2019-06-22,200.0,"Manhattan, Murray Hill",Large Cozy 1 BR Apartment In Midtown East,Entire home/apt
3,5178,Shunichi,2019-06-24,79.0,"Manhattan, Hell's Kitchen",Large Furnished Room Near B'way,private room
4,5238,Ben,2019-06-09,150.0,"Manhattan, Chinatown",Cute & Cozy Lower East Side 1 bdrm,Entire home/apt

In [65]:
df_all_merge.tail()

,listing_id,host_name,last_review,price,nbhood_full,description,room_type
25204,36425863,Rusaa,2019-07-07,129.0,"Manhattan, Upper East Side",Lovely Privet Bedroom with Privet Restroom,PRIVATE ROOM
25205,36427429,H Ai,2019-07-07,45.0,"Queens, Flushing",No.2 with queen size bed,PRIVATE ROOM
25206,36438336,Ben,2019-07-07,235.0,"Staten Island, Great Kills",Seas The Moment,Private room
25207,36442252,Blaine,2019-07-07,100.0,"Bronx, Mott Haven",1B-1B apartment near by Metro,Entire home/apt
25208,36455809,Christine,2019-07-08,30.0,"Brooklyn, Bushwick","Cozy Private Room in Bushwick, Brooklyn",Private room

In [67]:
df_all_merge.duplicated(subset = ['listing_id']).sum()

np.int64(0)